;;; cl-lookup-glossary.el --- View various documentation on Common Lisp

;; Copyright (C) 2004 Yuji 'bmonkey' Minejima <ggb01164@nifty.ne.jp>

;; Author: Yuji Minejima <ggb01164@nifty.ne.jp>
;; $Revision: 1.1 $
;; Keywords: local, lisp

;; This file is NOT part of GNU Emacs.

;; This program is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This program is distributed in the hope that it will be useful, but
;; WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;; General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs; see the file COPYING.  If not, write to the
;; Free Software Foundation, Inc., 59 Temple Place - Suite 330,
;; Boston, MA 02111-1307, USA.

;;; Commentary:



;;; Change Log:



;;; Code:
(require 'cl-lookup)

(mapc #'(lambda (entry)
          (destructuring-bind (name path) entry
            (let ((symbol (intern (downcase name) cl-lookup-obarray)))
              (if (boundp symbol)
                  (pushnew path (symbol-value symbol) :test #'equal)
                  (set symbol `(,path))))))
      '(("{()}" "26_glo_9.htm#OPCP")
        ("{absolute}" "26_glo_a.htm#absolute")
        ("{access}" "26_glo_a.htm#access")
        ("{accessibility}" "26_glo_a.htm#accessibility")
        ("{accessible}" "26_glo_a.htm#accessible")
        ("{accessor}" "26_glo_a.htm#accessor")
        ("{active}" "26_glo_a.htm#active")
        ("{actual adjustability}" "26_glo_a.htm#actual_adjustability")
        ("{actual argument}" "26_glo_a.htm#actual_argument")
        ("{actual array element type}" "26_glo_a.htm#actual_array_element_type")
        ("{actual complex part type}" "26_glo_a.htm#actual_complex_part_type")
        ("{actual parameter}" "26_glo_a.htm#actual_parameter")
        ("{actually adjustable}" "26_glo_a.htm#actually_adjustable")
        ("{adjustability}" "26_glo_a.htm#adjustability")
        ("{adjustable}" "26_glo_a.htm#adjustable")
        ("{after method}" "26_glo_a.htm#after_method")
        ("{alist}" "26_glo_a.htm#alist")
        ("{alphabetic}" "26_glo_a.htm#alphabetic")
        ("{alphanumeric}" "26_glo_a.htm#alphanumeric")
        ("{ampersand}" "26_glo_a.htm#ampersand")
        ("{anonymous}" "26_glo_a.htm#anonymous")
        ("{apparently uninterned}" "26_glo_a.htm#apparently_uninterned")
        ("{applicable}" "26_glo_a.htm#applicable")
        ("{applicable handler}" "26_glo_a.htm#applicable_handler")
        ("{applicable method}" "26_glo_a.htm#applicable_method")
        ("{applicable restart}" "26_glo_a.htm#applicable_restart")
        ("{apply}" "26_glo_a.htm#apply")
        ("{argument}" "26_glo_a.htm#argument")
        ("{argument evaluation order}" "26_glo_a.htm#argument_evaluation_order")
        ("{argument precedence order}" "26_glo_a.htm#argument_precedence_order")
        ("{around method}" "26_glo_a.htm#around_method")
        ("{array}" "26_glo_a.htm#array")
        ("{array element type}" "26_glo_a.htm#array_element_type")
        ("{array total size}" "26_glo_a.htm#array_total_size")
        ("{assign}" "26_glo_a.htm#assign")
        ("{association list}" "26_glo_a.htm#association_list")
        ("{asterisk}" "26_glo_a.htm#asterisk")
        ("{at-sign}" "26_glo_a.htm#at-sign")
        ("{atom}" "26_glo_a.htm#atom")
        ("{atomic}" "26_glo_a.htm#atomic")
        ("{atomic type specifier}" "26_glo_a.htm#atomic_type_specifier")
        ("{attribute}" "26_glo_a.htm#attribute")
        ("{aux variable}" "26_glo_a.htm#aux_variable")
        ("{auxiliary method}" "26_glo_a.htm#auxiliary_method")
        ("{backquote}" "26_glo_b.htm#backquote")
        ("{backslash}" "26_glo_b.htm#backslash")
        ("{base character}" "26_glo_b.htm#base_character")
        ("{base string}" "26_glo_b.htm#base_string")
        ("{before method}" "26_glo_b.htm#before_method")
        ("{bidirectional}" "26_glo_b.htm#bidirectional")
        ("{binary}" "26_glo_b.htm#binary")
        ("{bind}" "26_glo_b.htm#bind")
        ("{binding}" "26_glo_b.htm#binding")
        ("{bit}" "26_glo_b.htm#bit")
        ("{bit array}" "26_glo_b.htm#bit_array")
        ("{bit vector}" "26_glo_b.htm#bit_vector")
        ("{bit-wise logical operation specifier}" "26_glo_b.htm#bit-wise_logical_operation_specifier")
        ("{block}" "26_glo_b.htm#block")
        ("{block tag}" "26_glo_b.htm#block_tag")
        ("{boa lambda list}" "26_glo_b.htm#boa_lambda_list")
        ("{body parameter}" "26_glo_b.htm#body_parameter")
        ("{boolean}" "26_glo_b.htm#boolean")
        ("{boolean equivalent}" "26_glo_b.htm#boolean_equivalent")
        ("{bound}" "26_glo_b.htm#bound")
        ("{bound declaration}" "26_glo_b.htm#bound_declaration")
        ("{bounded}" "26_glo_b.htm#bounded")
        ("{bounding index}" "26_glo_b.htm#bounding_index")
        ("{bounding index designator}" "26_glo_b.htm#bounding_index_designator")
        ("{break loop}" "26_glo_b.htm#break_loop")
        ("{broadcast stream}" "26_glo_b.htm#broadcast_stream")
        ("{built-in class}" "26_glo_b.htm#built-in_class")
        ("{built-in type}" "26_glo_b.htm#built-in_type")
        ("{byte}" "26_glo_b.htm#byte")
        ("{byte specifier}" "26_glo_b.htm#byte_specifier")
        ("{cadr}" "26_glo_c.htm#cadr")
        ("{call}" "26_glo_c.htm#call")
        ("{captured initialization form}" "26_glo_c.htm#captured_initialization_form")
        ("{car}" "26_glo_c.htm#car")
        ("{case}" "26_glo_c.htm#case")
        ("{case sensitivity mode}" "26_glo_c.htm#case_sensitivity_mode")
        ("{catch}" "26_glo_c.htm#catch")
        ("{catch tag}" "26_glo_c.htm#catch_tag")
        ("{cddr}" "26_glo_c.htm#cddr")
        ("{cdr}" "26_glo_c.htm#cdr")
        ("{cell}" "26_glo_c.htm#cell")
        ("{character}" "26_glo_c.htm#character")
        ("{character code}" "26_glo_c.htm#character_code")
        ("{character designator}" "26_glo_c.htm#character_designator")
        ("{circular}" "26_glo_c.htm#circular")
        ("{circular list}" "26_glo_c.htm#circular_list")
        ("{class}" "26_glo_c.htm#class")
        ("{class designator}" "26_glo_c.htm#class_designator")
        ("{class precedence list}" "26_glo_c.htm#class_precedence_list")
        ("{close}" "26_glo_c.htm#close")
        ("{closed}" "26_glo_c.htm#closed")
        ("{closure}" "26_glo_c.htm#closure")
        ("{coalesce}" "26_glo_c.htm#coalesce")
        ("{code}" "26_glo_c.htm#code")
        ("{coerce}" "26_glo_c.htm#coerce")
        ("{colon}" "26_glo_c.htm#colon")
        ("{comma}" "26_glo_c.htm#comma")
        ("{compilation}" "26_glo_c.htm#compilation")
        ("{compilation environment}" "26_glo_c.htm#compilation_environment")
        ("{compilation unit}" "26_glo_c.htm#compilation_unit")
        ("{compile}" "26_glo_c.htm#compile")
        ("{compile time}" "26_glo_c.htm#compile_time")
        ("{compile time definition}" "26_glo_c.htm#compile-time_definition")
        ("{compiled code}" "26_glo_c.htm#compiled_code")
        ("{compiled file}" "26_glo_c.htm#compiled_file")
        ("{compiled function}" "26_glo_c.htm#compiled_function")
        ("{compiler}" "26_glo_c.htm#compiler")
        ("{compiler macro}" "26_glo_c.htm#compiler_macro")
        ("{compiler macro expansion}" "26_glo_c.htm#compiler_macro_expansion")
        ("{compiler macro form}" "26_glo_c.htm#compiler_macro_form")
        ("{compiler macro function}" "26_glo_c.htm#compiler_macro_function")
        ("{complex}" "26_glo_c.htm#complex")
        ("{complex float}" "26_glo_c.htm#complex_float")
        ("{complex part type}" "26_glo_c.htm#complex_part_type")
        ("{complex rational}" "26_glo_c.htm#complex_rational")
        ("{complex single float}" "26_glo_c.htm#complex_single_float")
        ("{composite stream}" "26_glo_c.htm#composite_stream")
        ("{compound form}" "26_glo_c.htm#compound_form")
        ("{compound type specifier}" "26_glo_c.htm#compound_type_specifier")
        ("{concatenated stream}" "26_glo_c.htm#concatenated_stream")
        ("{condition}" "26_glo_c.htm#condition")
        ("{condition designator}" "26_glo_c.htm#condition_designator")
        ("{condition handler}" "26_glo_c.htm#condition_handler")
        ("{condition reporter}" "26_glo_c.htm#condition_reporter")
        ("{conditional newline}" "26_glo_c.htm#conditional_newline")
        ("{conformance}" "26_glo_c.htm#conformance")
        ("{conforming code}" "26_glo_c.htm#conforming_code")
        ("{conforming implementation}" "26_glo_c.htm#conforming_implementation")
        ("{conforming processor}" "26_glo_c.htm#conforming_processor")
        ("{conforming program}" "26_glo_c.htm#conforming_program")
        ("{congruent}" "26_glo_c.htm#congruent")
        ("{cons}" "26_glo_c.htm#cons")
        ("{constant}" "26_glo_c.htm#constant")
        ("{constant form}" "26_glo_c.htm#constant_form")
        ("{constant object}" "26_glo_c.htm#constant_object")
        ("{constant variable}" "26_glo_c.htm#constant_variable")
        ("{constituent}" "26_glo_c.htm#constituent")
        ("{constituent trait}" "26_glo_c.htm#constituent_trait")
        ("{constructed stream}" "26_glo_c.htm#constructed_stream")
        ("{contagion}" "26_glo_c.htm#contagion")
        ("{continuable}" "26_glo_c.htm#continuable")
        ("{control form}" "26_glo_c.htm#control_form")
        ("{copy}" "26_glo_c.htm#copy")
        ("{correctable}" "26_glo_c.htm#correctable")
        ("{current input base}" "26_glo_c.htm#current_input_base")
        ("{current logical block}" "26_glo_c.htm#current_logical_block")
        ("{current output base}" "26_glo_c.htm#current_output_base")
        ("{current package}" "26_glo_c.htm#current_package")
        ("{current pprint dispatch table}" "26_glo_c.htm#current_pprint_dispatch_table")
        ("{current random state}" "26_glo_c.htm#current_random_state")
        ("{current readtable}" "26_glo_c.htm#current_readtable")
        ("{data type}" "26_glo_d.htm#data_type")
        ("{debug I/O}" "26_glo_d.htm#debug_iSLo")
        ("{debugger}" "26_glo_d.htm#debugger")
        ("{declaration}" "26_glo_d.htm#declaration")
        ("{declaration identifier}" "26_glo_d.htm#declaration_identifier")
        ("{declaration specifier}" "26_glo_d.htm#declaration_specifier")
        ("{declare}" "26_glo_d.htm#declare")
        ("{decline}" "26_glo_d.htm#decline")
        ("{decoded time}" "26_glo_d.htm#decoded_time")
        ("{default method}" "26_glo_d.htm#default_method")
        ("{defaulted initialization argument list}" "26_glo_d.htm#defaulted_initialization_argument_list")
        ("{define-method-combination arguments lambda list}" "26_glo_d.htm#define-method-combination_arguments_lambda_list")
        ("{define-modify-macro lambda list}" "26_glo_d.htm#define-modify-macro_lambda_list")
        ("{defined name}" "26_glo_d.htm#defined_name")
        ("{defining form}" "26_glo_d.htm#defining_form")
        ("{defsetf lambda list}" "26_glo_d.htm#defsetf_lambda_list")
        ("{deftype lambda list}" "26_glo_d.htm#deftype_lambda_list")
        ("{denormalized}" "26_glo_d.htm#denormalized")
        ("{derived type}" "26_glo_d.htm#derived_type")
        ("{derived type specifier}" "26_glo_d.htm#derived_type_specifier")
        ("{designator}" "26_glo_d.htm#designator")
        ("{destructive}" "26_glo_d.htm#destructive")
        ("{destructuring lambda list}" "26_glo_d.htm#destructuring_lambda_list")
        ("{different}" "26_glo_d.htm#different")
        ("{digit}" "26_glo_d.htm#digit")
        ("{dimension}" "26_glo_d.htm#dimension")
        ("{direct instance}" "26_glo_d.htm#direct_instance")
        ("{direct subclass}" "26_glo_d.htm#direct_subclass")
        ("{direct superclass}" "26_glo_d.htm#direct_superclass")
        ("{disestablish}" "26_glo_d.htm#disestablish")
        ("{disjoint}" "26_glo_d.htm#disjoint")
        ("{dispatching macro character}" "26_glo_d.htm#dispatching_macro_character")
        ("{displaced array}" "26_glo_d.htm#displaced_array")
        ("{distinct}" "26_glo_d.htm#distinct")
        ("{documentation string}" "26_glo_d.htm#documentation_string")
        ("{dot}" "26_glo_d.htm#dot")
        ("{dotted list}" "26_glo_d.htm#dotted_list")
        ("{dotted pair}" "26_glo_d.htm#dotted_pair")
        ("{double float}" "26_glo_d.htm#double_float")
        ("{double-quote}" "26_glo_d.htm#double-quote")
        ("{dynamic binding}" "26_glo_d.htm#dynamic_binding")
        ("{dynamic environment}" "26_glo_d.htm#dynamic_environment")
        ("{dynamic extent}" "26_glo_d.htm#dynamic_extent")
        ("{dynamic scope}" "26_glo_d.htm#dynamic_scope")
        ("{dynamic variable}" "26_glo_d.htm#dynamic_variable")
        ("{echo stream}" "26_glo_e.htm#echo_stream")
        ("{effective method}" "26_glo_e.htm#effective_method")
        ("{element}" "26_glo_e.htm#element")
        ("{element type}" "26_glo_e.htm#element_type")
        ("{em}" "26_glo_e.htm#em")
        ("{empty list}" "26_glo_e.htm#empty_list")
        ("{empty type}" "26_glo_e.htm#empty_type")
        ("{end of file}" "26_glo_e.htm#end_of_file")
        ("{environment}" "26_glo_e.htm#environment")
        ("{environment object}" "26_glo_e.htm#environment_object")
        ("{environment parameter}" "26_glo_e.htm#environment_parameter")
        ("{error}" "26_glo_e.htm#error")
        ("{error output}" "26_glo_e.htm#error_output")
        ("{escape}" "26_glo_e.htm#escape")
        ("{establish}" "26_glo_e.htm#establish")
        ("{evaluate}" "26_glo_e.htm#evaluate")
        ("{evaluation}" "26_glo_e.htm#evaluation")
        ("{evaluation environment}" "26_glo_e.htm#evaluation_environment")
        ("{execute}" "26_glo_e.htm#execute")
        ("{execution time}" "26_glo_e.htm#execution_time")
        ("{exhaustive partition}" "26_glo_e.htm#exhaustive_partition")
        ("{exhaustive union}" "26_glo_e.htm#exhaustive_union")
        ("{exit point}" "26_glo_e.htm#exit_point")
        ("{explicit return}" "26_glo_e.htm#explicit_return")
        ("{explicit use}" "26_glo_e.htm#explicit_use")
        ("{exponent marker}" "26_glo_e.htm#exponent_marker")
        ("{export}" "26_glo_e.htm#export")
        ("{exported}" "26_glo_e.htm#exported")
        ("{expressed adjustability}" "26_glo_e.htm#expressed_adjustability")
        ("{expressed array element type}" "26_glo_e.htm#expressed_array_element_type")
        ("{expressed complex part type}" "26_glo_e.htm#expressed_complex_part_type")
        ("{expression}" "26_glo_e.htm#expression")
        ("{expressly adjustable}" "26_glo_e.htm#expressly_adjustable")
        ("{extended character}" "26_glo_e.htm#extended_character")
        ("{extended function designator}" "26_glo_e.htm#extended_function_designator")
        ("{extended lambda list}" "26_glo_e.htm#extended_lambda_list")
        ("{extension}" "26_glo_e.htm#extension")
        ("{extent}" "26_glo_e.htm#extent")
        ("{external file format}" "26_glo_e.htm#external_file_format")
        ("{external file format designator}" "26_glo_e.htm#external_file_format_designator")
        ("{external symbol}" "26_glo_e.htm#external_symbol")
        ("{externalizable object}" "26_glo_e.htm#externalizable_object")
        ("{false}" "26_glo_f.htm#false")
        ("{fbound}" "26_glo_f.htm#fbound")
        ("{feature}" "26_glo_f.htm#feature")
        ("{feature expression}" "26_glo_f.htm#feature_expression")
        ("{features list}" "26_glo_f.htm#features_list")
        ("{file}" "26_glo_f.htm#file")
        ("{file compiler}" "26_glo_f.htm#file_compiler")
        ("{file position}" "26_glo_f.htm#file_position")
        ("{file position designator}" "26_glo_f.htm#file_position_designator")
        ("{file stream}" "26_glo_f.htm#file_stream")
        ("{file system}" "26_glo_f.htm#file_system")
        ("{filename}" "26_glo_f.htm#filename")
        ("{fill pointer}" "26_glo_f.htm#fill_pointer")
        ("{finite}" "26_glo_f.htm#finite")
        ("{fixnum}" "26_glo_f.htm#fixnum")
        ("{float}" "26_glo_f.htm#float")
        ("{for-value}" "26_glo_f.htm#for-value")
        ("{form}" "26_glo_f.htm#form")
        ("{formal argument}" "26_glo_f.htm#formal_argument")
        ("{formal parameter}" "26_glo_f.htm#formal_parameter")
        ("{format}" "26_glo_f.htm#format")
        ("{format argument}" "26_glo_f.htm#format_argument")
        ("{format control}" "26_glo_f.htm#format_control")
        ("{format directive}" "26_glo_f.htm#format_directive")
        ("{format string}" "26_glo_f.htm#format_string")
        ("{free declaration}" "26_glo_f.htm#free_declaration")
        ("{fresh}" "26_glo_f.htm#fresh")
        ("{freshline}" "26_glo_f.htm#freshline")
        ("{funbound}" "26_glo_f.htm#funbound")
        ("{function}" "26_glo_f.htm#function")
        ("{function block name}" "26_glo_f.htm#function_block_name")
        ("{function cell}" "26_glo_f.htm#function_cell")
        ("{function designator}" "26_glo_f.htm#function_designator")
        ("{function form}" "26_glo_f.htm#function_form")
        ("{function name}" "26_glo_f.htm#function_name")
        ("{functional evaluation}" "26_glo_f.htm#functional_evaluation")
        ("{functional value}" "26_glo_f.htm#functional_value")
        ("{further compilation}" "26_glo_f.htm#further_compilation")
        ("{general}" "26_glo_g.htm#general")
        ("{generalized boolean}" "26_glo_g.htm#generalized_boolean")
        ("{generalized instance}" "26_glo_g.htm#generalized_instance")
        ("{generalized reference}" "26_glo_g.htm#generalized_reference")
        ("{generalized synonym stream}" "26_glo_g.htm#generalized_synonym_stream")
        ("{generic function}" "26_glo_g.htm#generic_function")
        ("{generic function lambda list}" "26_glo_g.htm#generic_function_lambda_list")
        ("{gensym}" "26_glo_g.htm#gensym")
        ("{global declaration}" "26_glo_g.htm#global_declaration")
        ("{global environment}" "26_glo_g.htm#global_environment")
        ("{global variable}" "26_glo_g.htm#global_variable")
        ("{glyph}" "26_glo_g.htm#glyph")
        ("{go}" "26_glo_g.htm#go")
        ("{go point}" "26_glo_g.htm#go_point")
        ("{go tag}" "26_glo_g.htm#go_tag")
        ("{graphic}" "26_glo_g.htm#graphic")
        ("{handle}" "26_glo_h.htm#handle")
        ("{handler}" "26_glo_h.htm#handler")
        ("{hash table}" "26_glo_h.htm#hash_table")
        ("{home package}" "26_glo_h.htm#home_package")
        ("{I/O customization variable}" "26_glo_i.htm#iSLo_customization_variable")
        ("{identical}" "26_glo_i.htm#identical")
        ("{identifier}" "26_glo_i.htm#identifier")
        ("{immutable}" "26_glo_i.htm#immutable")
        ("{implementation}" "26_glo_i.htm#implementation")
        ("{implementation limit}" "26_glo_i.htm#implementation_limit")
        ("{implementation-defined}" "26_glo_i.htm#implementation-defined")
        ("{implementation-dependent}" "26_glo_i.htm#implementation-dependent")
        ("{implementation-independent}" "26_glo_i.htm#implementation-independent")
        ("{implicit block}" "26_glo_i.htm#implicit_block")
        ("{implicit compilation}" "26_glo_i.htm#implicit_compilation")
        ("{implicit progn}" "26_glo_i.htm#implicit_progn")
        ("{implicit tagbody}" "26_glo_i.htm#implicit_tagbody")
        ("{import}" "26_glo_i.htm#import")
        ("{improper list}" "26_glo_i.htm#improper_list")
        ("{inaccessible}" "26_glo_i.htm#inaccessible")
        ("{indefinite extent}" "26_glo_i.htm#indefinite_extent")
        ("{indefinite scope}" "26_glo_i.htm#indefinite_scope")
        ("{indicator}" "26_glo_i.htm#indicator")
        ("{indirect instance}" "26_glo_i.htm#indirect_instance")
        ("{inherit}" "26_glo_i.htm#inherit")
        ("{initial pprint dispatch table}" "26_glo_i.htm#initial_pprint_dispatch_table")
        ("{initial readtable}" "26_glo_i.htm#initial_readtable")
        ("{initialization argument list}" "26_glo_i.htm#initialization_argument_list")
        ("{initialization form}" "26_glo_i.htm#initialization_form")
        ("{input}" "26_glo_i.htm#input")
        ("{instance}" "26_glo_i.htm#instance")
        ("{integer}" "26_glo_i.htm#integer")
        ("{interactive stream}" "26_glo_i.htm#interactive_stream")
        ("{intern}" "26_glo_i.htm#intern")
        ("{internal symbol}" "26_glo_i.htm#internal_symbol")
        ("{internal time}" "26_glo_i.htm#internal_time")
        ("{internal time unit}" "26_glo_i.htm#internal_time_unit")
        ("{interned}" "26_glo_i.htm#interned")
        ("{interpreted function}" "26_glo_i.htm#interpreted_function")
        ("{interpreted implementation}" "26_glo_i.htm#interpreted_implementation")
        ("{interval designator}" "26_glo_i.htm#interval_designator")
        ("{invalid}" "26_glo_i.htm#invalid")
        ("{iteration form}" "26_glo_i.htm#iteration_form")
        ("{iteration variable}" "26_glo_i.htm#iteration_variable")
        ("{key}" "26_glo_k.htm#key")
        ("{keyword}" "26_glo_k.htm#keyword")
        ("{keyword parameter}" "26_glo_k.htm#keyword_parameter")
        ("{keyword/value pair}" "26_glo_k.htm#keywordSLvalue_pair")
        ("{lambda combination}" "26_glo_l.htm#lambda_combination")
        ("{lambda expression}" "26_glo_l.htm#lambda_expression")
        ("{lambda form}" "26_glo_l.htm#lambda_form")
        ("{lambda list}" "26_glo_l.htm#lambda_list")
        ("{lambda list keyword}" "26_glo_l.htm#lambda_list_keyword")
        ("{lambda variable}" "26_glo_l.htm#lambda_variable")
        ("{leaf}" "26_glo_l.htm#leaf")
        ("{leap seconds}" "26_glo_l.htm#leap_seconds")
        ("{left-parenthesis}" "26_glo_l.htm#left-parenthesis")
        ("{length}" "26_glo_l.htm#length")
        ("{lexical binding}" "26_glo_l.htm#lexical_binding")
        ("{lexical closure}" "26_glo_l.htm#lexical_closure")
        ("{lexical environment}" "26_glo_l.htm#lexical_environment")
        ("{lexical scope}" "26_glo_l.htm#lexical_scope")
        ("{lexical variable}" "26_glo_l.htm#lexical_variable")
        ("{lisp image}" "26_glo_l.htm#lisp_image")
        ("{lisp printer}" "26_glo_l.htm#lisp_printer")
        ("{lisp read-eval-print loop}" "26_glo_l.htm#lisp_read-eval-print_loop")
        ("{lisp reader}" "26_glo_l.htm#lisp_reader")
        ("{list}" "26_glo_l.htm#list")
        ("{list designator}" "26_glo_l.htm#list_designator")
        ("{list structure}" "26_glo_l.htm#list_structure")
        ("{literal}" "26_glo_l.htm#literal")
        ("{load}" "26_glo_l.htm#load")
        ("{load time}" "26_glo_l.htm#load_time")
        ("{load time value}" "26_glo_l.htm#load_time_value")
        ("{loader}" "26_glo_l.htm#loader")
        ("{local declaration}" "26_glo_l.htm#local_declaration")
        ("{local precedence order}" "26_glo_l.htm#local_precedence_order")
        ("{local slot}" "26_glo_l.htm#local_slot")
        ("{logical block}" "26_glo_l.htm#logical_block")
        ("{logical host}" "26_glo_l.htm#logical_host")
        ("{logical host designator}" "26_glo_l.htm#logical_host_designator")
        ("{logical pathname}" "26_glo_l.htm#logical_pathname")
        ("{long float}" "26_glo_l.htm#long_float")
        ("{loop keyword}" "26_glo_l.htm#loop_keyword")
        ("{lowercase}" "26_glo_l.htm#lowercase")
        ("{macro}" "26_glo_m.htm#macro")
        ("{macro character}" "26_glo_m.htm#macro_character")
        ("{macro expansion}" "26_glo_m.htm#macro_expansion")
        ("{macro form}" "26_glo_m.htm#macro_form")
        ("{macro function}" "26_glo_m.htm#macro_function")
        ("{macro lambda list}" "26_glo_m.htm#macro_lambda_list")
        ("{macro name}" "26_glo_m.htm#macro_name")
        ("{macroexpand hook}" "26_glo_m.htm#macroexpand_hook")
        ("{mapping}" "26_glo_m.htm#mapping")
        ("{metaclass}" "26_glo_m.htm#metaclass")
        ("{metaobject protocol}" "26_glo_m.htm#metaobject_protocol")
        ("{method}" "26_glo_m.htm#method")
        ("{method combination}" "26_glo_m.htm#method_combination")
        ("{method-defining form}" "26_glo_m.htm#method-defining_form")
        ("{method-defining operator}" "26_glo_m.htm#method-defining_operator")
        ("{minimal compilation}" "26_glo_m.htm#minimal_compilation")
        ("{modified lambda list}" "26_glo_m.htm#modified_lambda_list")
        ("{most recent}" "26_glo_m.htm#most_recent")
        ("{multiple escape}" "26_glo_m.htm#multiple_escape")
        ("{multiple values}" "26_glo_m.htm#multiple_values")
        ("{name}" "26_glo_n.htm#name")
        ("{named constant}" "26_glo_n.htm#named_constant")
        ("{namespace}" "26_glo_n.htm#namespace")
        ("{namestring}" "26_glo_n.htm#namestring")
        ("{newline}" "26_glo_n.htm#newline")
        ("{next method}" "26_glo_n.htm#next_method")
        ("{nickname}" "26_glo_n.htm#nickname")
        ("{nil}" "26_glo_n.htm#nil")
        ("{non-atomic}" "26_glo_n.htm#non-atomic")
        ("{non-constant variable}" "26_glo_n.htm#non-constant_variable")
        ("{non-correctable}" "26_glo_n.htm#non-correctable")
        ("{non-empty}" "26_glo_n.htm#non-empty")
        ("{non-generic function}" "26_glo_n.htm#non-generic_function")
        ("{non-graphic}" "26_glo_n.htm#non-graphic")
        ("{non-list}" "26_glo_n.htm#non-list")
        ("{non-local exit}" "26_glo_n.htm#non-local_exit")
        ("{non-nil}" "26_glo_n.htm#non-nil")
        ("{non-null lexical environment}" "26_glo_n.htm#non-null_lexical_environment")
        ("{non-simple}" "26_glo_n.htm#non-simple")
        ("{non-terminating}" "26_glo_n.htm#non-terminating")
        ("{non-top-level form}" "26_glo_n.htm#non-top-level_form")
        ("{normal return}" "26_glo_n.htm#normal_return")
        ("{normalized}" "26_glo_n.htm#normalized")
        ("{null}" "26_glo_n.htm#null")
        ("{null lexical environment}" "26_glo_n.htm#null_lexical_environment")
        ("{number}" "26_glo_n.htm#number")
        ("{numeric}" "26_glo_n.htm#numeric")
        ("{object}" "26_glo_o.htm#object")
        ("{object-traversing}" "26_glo_o.htm#object-traversing")
        ("{open}" "26_glo_o.htm#open")
        ("{operator}" "26_glo_o.htm#operator")
        ("{optimize quality}" "26_glo_o.htm#optimize_quality")
        ("{optional parameter}" "26_glo_o.htm#optional_parameter")
        ("{ordinary function}" "26_glo_o.htm#ordinary_function")
        ("{ordinary lambda list}" "26_glo_o.htm#ordinary_lambda_list")
        ("{otherwise inaccessible part}" "26_glo_o.htm#otherwise_inaccessible_part")
        ("{output}" "26_glo_o.htm#output")
        ("{package}" "26_glo_p.htm#package")
        ("{package cell}" "26_glo_p.htm#package_cell")
        ("{package designator}" "26_glo_p.htm#package_designator")
        ("{package marker}" "26_glo_p.htm#package_marker")
        ("{package prefix}" "26_glo_p.htm#package_prefix")
        ("{package registry}" "26_glo_p.htm#package_registry")
        ("{pairwise}" "26_glo_p.htm#pairwise")
        ("{parallel}" "26_glo_p.htm#parallel")
        ("{parameter}" "26_glo_p.htm#parameter")
        ("{parameter specializer}" "26_glo_p.htm#parameter_specializer")
        ("{parameter specializer name}" "26_glo_p.htm#parameter_specializer_name")
        ("{pathname}" "26_glo_p.htm#pathname")
        ("{pathname designator}" "26_glo_p.htm#pathname_designator")
        ("{physical pathname}" "26_glo_p.htm#physical_pathname")
        ("{place}" "26_glo_p.htm#place")
        ("{plist}" "26_glo_p.htm#plist")
        ("{portable}" "26_glo_p.htm#portable")
        ("{potential copy}" "26_glo_p.htm#potential_copy")
        ("{potential number}" "26_glo_p.htm#potential_number")
        ("{pprint dispatch table}" "26_glo_p.htm#pprint_dispatch_table")
        ("{predicate}" "26_glo_p.htm#predicate")
        ("{present}" "26_glo_p.htm#present")
        ("{pretty print}" "26_glo_p.htm#pretty_print")
        ("{pretty printer}" "26_glo_p.htm#pretty_printer")
        ("{pretty printing stream}" "26_glo_p.htm#pretty_printing_stream")
        ("{primary method}" "26_glo_p.htm#primary_method")
        ("{primary value}" "26_glo_p.htm#primary_value")
        ("{principal}" "26_glo_p.htm#principal")
        ("{print name}" "26_glo_p.htm#print_name")
        ("{printer control variable}" "26_glo_p.htm#printer_control_variable")
        ("{printer escaping}" "26_glo_p.htm#printer_escaping")
        ("{printing}" "26_glo_p.htm#printing")
        ("{process}" "26_glo_p.htm#process")
        ("{processor}" "26_glo_p.htm#processor")
        ("{proclaim}" "26_glo_p.htm#proclaim")
        ("{proclamation}" "26_glo_p.htm#proclamation")
        ("{prog tag}" "26_glo_p.htm#prog_tag")
        ("{program}" "26_glo_p.htm#program")
        ("{programmer}" "26_glo_p.htm#programmer")
        ("{programmer code}" "26_glo_p.htm#programmer_code")
        ("{proper list}" "26_glo_p.htm#proper_list")
        ("{proper name}" "26_glo_p.htm#proper_name")
        ("{proper sequence}" "26_glo_p.htm#proper_sequence")
        ("{proper subtype}" "26_glo_p.htm#proper_subtype")
        ("{property}" "26_glo_p.htm#property")
        ("{property indicator}" "26_glo_p.htm#property_indicator")
        ("{property list}" "26_glo_p.htm#property_list")
        ("{property value}" "26_glo_p.htm#property_value")
        ("{purports to conform}" "26_glo_p.htm#purports_to_conform")
        ("{qualified method}" "26_glo_q.htm#qualified_method")
        ("{qualifier}" "26_glo_q.htm#qualifier")
        ("{query I/O}" "26_glo_q.htm#query_iSLo")
        ("{quoted object}" "26_glo_q.htm#quoted_object")
        ("{radix}" "26_glo_r.htm#radix")
        ("{random state}" "26_glo_r.htm#random_state")
        ("{rank}" "26_glo_r.htm#rank")
        ("{ratio}" "26_glo_r.htm#ratio")
        ("{ratio marker}" "26_glo_r.htm#ratio_marker")
        ("{rational}" "26_glo_r.htm#rational")
        ("{read}" "26_glo_r.htm#read")
        ("{readably}" "26_glo_r.htm#readably")
        ("{reader}" "26_glo_r.htm#reader")
        ("{reader macro}" "26_glo_r.htm#reader_macro")
        ("{reader macro function}" "26_glo_r.htm#reader_macro_function")
        ("{readtable}" "26_glo_r.htm#readtable")
        ("{readtable case}" "26_glo_r.htm#readtable_case")
        ("{readtable designator}" "26_glo_r.htm#readtable_designator")
        ("{recognizable subtype}" "26_glo_r.htm#recognizable_subtype")
        ("{reference}" "26_glo_r.htm#reference")
        ("{registered package}" "26_glo_r.htm#registered_package")
        ("{relative}" "26_glo_r.htm#relative")
        ("{repertoire}" "26_glo_r.htm#repertoire")
        ("{report}" "26_glo_r.htm#report")
        ("{report message}" "26_glo_r.htm#report_message")
        ("{required parameter}" "26_glo_r.htm#required_parameter")
        ("{rest list}" "26_glo_r.htm#rest_list")
        ("{rest parameter}" "26_glo_r.htm#rest_parameter")
        ("{restart}" "26_glo_r.htm#restart")
        ("{restart designator}" "26_glo_r.htm#restart_designator")
        ("{restart function}" "26_glo_r.htm#restart_function")
        ("{return}" "26_glo_r.htm#return")
        ("{return value}" "26_glo_r.htm#return_value")
        ("{right-parenthesis}" "26_glo_r.htm#right-parenthesis")
        ("{run time}" "26_glo_r.htm#run_time")
        ("{run-time compiler}" "26_glo_r.htm#run-time_compiler")
        ("{run-time definition}" "26_glo_r.htm#run-time_definition")
        ("{run-time environment}" "26_glo_r.htm#run-time_environment")
        ("{safe}" "26_glo_s.htm#safe")
        ("{safe call}" "26_glo_s.htm#safe_call")
        ("{same}" "26_glo_s.htm#same")
        ("{satisfy the test}" "26_glo_s.htm#satisfy_the_test")
        ("{scope}" "26_glo_s.htm#scope")
        ("{script}" "26_glo_s.htm#script")
        ("{secondary value}" "26_glo_s.htm#secondary_value")
        ("{section}" "26_glo_s.htm#section")
        ("{self-evaluating object}" "26_glo_s.htm#self-evaluating_object")
        ("{semi-standard}" "26_glo_s.htm#semi-standard")
        ("{semicolon}" "26_glo_s.htm#semicolon")
        ("{sequence}" "26_glo_s.htm#sequence")
        ("{sequence function}" "26_glo_s.htm#sequence_function")
        ("{sequential}" "26_glo_s.htm#sequential")
        ("{sequentially}" "26_glo_s.htm#sequentially")
        ("{serious condition}" "26_glo_s.htm#serious_condition")
        ("{session}" "26_glo_s.htm#session")
        ("{set}" "26_glo_s.htm#set")
        ("{setf expander}" "26_glo_s.htm#setf_expander")
        ("{setf expansion}" "26_glo_s.htm#setf_expansion")
        ("{setf function}" "26_glo_s.htm#setf_function")
        ("{setf function name}" "26_glo_s.htm#setf_function_name")
        ("{shadow}" "26_glo_s.htm#shadow")
        ("{shadowing symbol}" "26_glo_s.htm#shadowing_symbol")
        ("{shadowing symbols list}" "26_glo_s.htm#shadowing_symbols_list")
        ("{shared slot}" "26_glo_s.htm#shared_slot")
        ("{sharpsign}" "26_glo_s.htm#sharpsign")
        ("{short float}" "26_glo_s.htm#short_float")
        ("{sign}" "26_glo_s.htm#sign")
        ("{signal}" "26_glo_s.htm#signal")
        ("{signature}" "26_glo_s.htm#signature")
        ("{similar}" "26_glo_s.htm#similar")
        ("{similarity}" "26_glo_s.htm#similarity")
        ("{simple}" "26_glo_s.htm#simple")
        ("{simple array}" "26_glo_s.htm#simple_array")
        ("{simple bit array}" "26_glo_s.htm#simple_bit_array")
        ("{simple bit vector}" "26_glo_s.htm#simple_bit_vector")
        ("{simple condition}" "26_glo_s.htm#simple_condition")
        ("{simple general vector}" "26_glo_s.htm#simple_general_vector")
        ("{simple string}" "26_glo_s.htm#simple_string")
        ("{simple vector}" "26_glo_s.htm#simple_vector")
        ("{single escape}" "26_glo_s.htm#single_escape")
        ("{single float}" "26_glo_s.htm#single_float")
        ("{single-quote}" "26_glo_s.htm#single-quote")
        ("{singleton}" "26_glo_s.htm#singleton")
        ("{situation}" "26_glo_s.htm#situation")
        ("{slash}" "26_glo_s.htm#slash")
        ("{slot}" "26_glo_s.htm#slot")
        ("{slot specifier}" "26_glo_s.htm#slot_specifier")
        ("{source code}" "26_glo_s.htm#source_code")
        ("{source file}" "26_glo_s.htm#source_file")
        ("{space}" "26_glo_s.htm#space")
        ("{special form}" "26_glo_s.htm#special_form")
        ("{special operator}" "26_glo_s.htm#special_operator")
        ("{special variable}" "26_glo_s.htm#special_variable")
        ("{specialize}" "26_glo_s.htm#specialize")
        ("{specialized}" "26_glo_s.htm#specialized")
        ("{specialized lambda list}" "26_glo_s.htm#specialized_lambda_list")
        ("{spreadable argument list designator}" "26_glo_s.htm#spreadable_argument_list_designator")
        ("{stack allocate}" "26_glo_s.htm#stack_allocate")
        ("{stack-allocated}" "26_glo_s.htm#stack-allocated")
        ("{standard character}" "26_glo_s.htm#standard_character")
        ("{standard class}" "26_glo_s.htm#standard_class")
        ("{standard generic function}" "26_glo_s.htm#standard_generic_function")
        ("{standard input}" "26_glo_s.htm#standard_input")
        ("{standard method combination}" "26_glo_s.htm#standard_method_combination")
        ("{standard object}" "26_glo_s.htm#standard_object")
        ("{standard output}" "26_glo_s.htm#standard_output")
        ("{standard pprint dispatch table}" "26_glo_s.htm#standard_pprint_dispatch_table")
        ("{standard readtable}" "26_glo_s.htm#standard_readtable")
        ("{standard syntax}" "26_glo_s.htm#standard_syntax")
        ("{standardized}" "26_glo_s.htm#standardized")
        ("{startup environment}" "26_glo_s.htm#startup_environment")
        ("{step}" "26_glo_s.htm#step")
        ("{stream}" "26_glo_s.htm#stream")
        ("{stream associated with a file}" "26_glo_s.htm#stream_associated_with_a_file")
        ("{stream designator}" "26_glo_s.htm#stream_designator")
        ("{stream element type}" "26_glo_s.htm#stream_element_type")
        ("{stream variable}" "26_glo_s.htm#stream_variable")
        ("{stream variable designator}" "26_glo_s.htm#stream_variable_designator")
        ("{string}" "26_glo_s.htm#string")
        ("{string designator}" "26_glo_s.htm#string_designator")
        ("{string equal}" "26_glo_s.htm#string_equal")
        ("{string stream}" "26_glo_s.htm#string_stream")
        ("{structure}" "26_glo_s.htm#structure")
        ("{structure class}" "26_glo_s.htm#structure_class")
        ("{structure name}" "26_glo_s.htm#structure_name")
        ("{style warning}" "26_glo_s.htm#style_warning")
        ("{subclass}" "26_glo_s.htm#subclass")
        ("{subexpression}" "26_glo_s.htm#subexpression")
        ("{subform}" "26_glo_s.htm#subform")
        ("{subrepertoire}" "26_glo_s.htm#subrepertoire")
        ("{subtype}" "26_glo_s.htm#subtype")
        ("{superclass}" "26_glo_s.htm#superclass")
        ("{supertype}" "26_glo_s.htm#supertype")
        ("{supplied-p parameter}" "26_glo_s.htm#supplied-p_parameter")
        ("{symbol}" "26_glo_s.htm#symbol")
        ("{symbol macro}" "26_glo_s.htm#symbol_macro")
        ("{synonym stream}" "26_glo_s.htm#synonym_stream")
        ("{synonym stream symbol}" "26_glo_s.htm#synonym_stream_symbol")
        ("{syntax type}" "26_glo_s.htm#syntax_type")
        ("{system class}" "26_glo_s.htm#system_class")
        ("{system code}" "26_glo_s.htm#system_code")
        ("{t}" "26_glo_t.htm#t")
        ("{tag}" "26_glo_t.htm#tag")
        ("{tail}" "26_glo_t.htm#tail")
        ("{target}" "26_glo_t.htm#target")
        ("{terminal I/O}" "26_glo_t.htm#terminal_iSLo")
        ("{terminating}" "26_glo_t.htm#terminating")
        ("{tertiary value}" "26_glo_t.htm#tertiary_value")
        ("{throw}" "26_glo_t.htm#throw")
        ("{tilde}" "26_glo_t.htm#tilde")
        ("{time}" "26_glo_t.htm#time")
        ("{time zone}" "26_glo_t.htm#time_zone")
        ("{token}" "26_glo_t.htm#token")
        ("{top level form}" "26_glo_t.htm#top_level_form")
        ("{trace output}" "26_glo_t.htm#trace_output")
        ("{tree}" "26_glo_t.htm#tree")
        ("{tree structure}" "26_glo_t.htm#tree_structure")
        ("{true}" "26_glo_t.htm#true")
        ("{truename}" "26_glo_t.htm#truename")
        ("{two-way stream}" "26_glo_t.htm#two-way_stream")
        ("{type}" "26_glo_t.htm#type")
        ("{type declaration}" "26_glo_t.htm#type_declaration")
        ("{type equivalent}" "26_glo_t.htm#type_equivalent")
        ("{type expand}" "26_glo_t.htm#type_expand")
        ("{type specifier}" "26_glo_t.htm#type_specifier")
        ("{unbound}" "26_glo_u.htm#unbound")
        ("{unbound variable}" "26_glo_u.htm#unbound_variable")
        ("{undefined function}" "26_glo_u.htm#undefined_function")
        ("{unintern}" "26_glo_u.htm#unintern")
        ("{uninterned}" "26_glo_u.htm#uninterned")
        ("{universal time}" "26_glo_u.htm#universal_time")
        ("{unqualified method}" "26_glo_u.htm#unqualified_method")
        ("{unregistered package}" "26_glo_u.htm#unregistered_package")
        ("{unsafe}" "26_glo_u.htm#unsafe")
        ("{unsafe call}" "26_glo_u.htm#unsafe_call")
        ("{upgrade}" "26_glo_u.htm#upgrade")
        ("{upgraded array element type}" "26_glo_u.htm#upgraded_array_element_type")
        ("{upgraded complex part type}" "26_glo_u.htm#upgraded_complex_part_type")
        ("{uppercase}" "26_glo_u.htm#uppercase")
        ("{use}" "26_glo_u.htm#use")
        ("{use list}" "26_glo_u.htm#use_list")
        ("{user}" "26_glo_u.htm#user")
        ("{valid array dimension}" "26_glo_v.htm#valid_array_dimension")
        ("{valid array index}" "26_glo_v.htm#valid_array_index")
        ("{valid array row-major index}" "26_glo_v.htm#valid_array_row-major_index")
        ("{valid fill pointer}" "26_glo_v.htm#valid_fill_pointer")
        ("{valid logical pathname host}" "26_glo_v.htm#valid_logical_pathname_host")
        ("{valid pathname device}" "26_glo_v.htm#valid_pathname_device")
        ("{valid pathname directory}" "26_glo_v.htm#valid_pathname_directory")
        ("{valid pathname host}" "26_glo_v.htm#valid_pathname_host")
        ("{valid pathname name}" "26_glo_v.htm#valid_pathname_name")
        ("{valid pathname type}" "26_glo_v.htm#valid_pathname_type")
        ("{valid pathname version}" "26_glo_v.htm#valid_pathname_version")
        ("{valid physical pathname host}" "26_glo_v.htm#valid_physical_pathname_host")
        ("{valid sequence index}" "26_glo_v.htm#valid_sequence_index")
        ("{value}" "26_glo_v.htm#value")
        ("{value cell}" "26_glo_v.htm#value_cell")
        ("{variable}" "26_glo_v.htm#variable")
        ("{vector}" "26_glo_v.htm#vector")
        ("{vertical-bar}" "26_glo_v.htm#vertical-bar")
        ("{whitespace}" "26_glo_w.htm#whitespace")
        ("{wild}" "26_glo_w.htm#wild")
        ("{write}" "26_glo_w.htm#write")
        ("{writer}" "26_glo_w.htm#writer")
        ("{yield}" "26_glo_y.htm#yield")))

(provide 'cl-lookup-glossary)

;;; cl-lookup-glossary.el ends here
